//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerhatPoturCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Careers
    {
        public int CareerID { get; set; }
        public string CompanyName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
    }
}
