//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerhatPoturCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kariyer
    {
        public int Id { get; set; }
        public string Firma_Adi { get; set; }
        public Nullable<System.DateTime> Start_Tarih { get; set; }
        public Nullable<System.DateTime> Fınısh_Tarih { get; set; }
        public string Pozisyon { get; set; }
        public string Acıklama { get; set; }
        public string Firma_Adres { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
