//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerhatPoturCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeler
    {
        public int Id { get; set; }
        public string Baslık { get; set; }
        public string Ad { get; set; }
        public string Acıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public byte[] Anaresim { get; set; }
        public byte[] Altresim { get; set; }
        public Nullable<int> fk_katId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
