//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerhatPoturCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedias
    {
        public int MediaID { get; set; }
        public string MediaName { get; set; }
        public string MediaLink { get; set; }
        public string MediaClass { get; set; }
    }
}
